# Generated by Django 4.2.9 on 2025-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_chart", models.BooleanField(default=False)),
                ("is_table", models.BooleanField(default=False)),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bar", "Bar Chart"),
                            ("area", "Area Chart"),
                            ("pie", "Circular Chart"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("ajax_url", models.CharField(max_length=350, null=True)),
                ("page_url", models.CharField(max_length=350, null=True)),
                ("is_fillter", models.BooleanField(default=False)),
                ("fillter_value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
