# Generated by Django 4.2.9 on 2025-06-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_dashboardcomponent_delete_product"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="dashboardcomponent",
            table="dashboardcomponent",
        ),
    ]
