# Generated by Django 4.2.9 on 2025-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_dashboardcomponent_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="URLRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url_pattern", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("show_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "unique_together": {("url_pattern", "name")},
            },
        ),
    ]
