# Generated by Django 4.2.9 on 2025-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_info", "0002_customerlist_customerlistitem_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Point",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "point_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("product_upload", "Product Upload"),
                            ("product_review", "Product Review"),
                            ("product_scan", "Product Scan"),
                            ("product_share", "Product Share"),
                            ("profile_completion", "Profile Completion"),
                            ("app_referral", "App Referral"),
                            ("referred_by", "Referred By"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("ref_customer", models.BigIntegerField(blank=True, null=True)),
                ("points", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "points",
                "managed": False,
            },
        ),
    ]
